### ISSUE TITLE
System.configuration could not be resolved

### ISSUE THREAD

**Issue by cemremengu** [basho/riak-dotnet-client#332]
I am trying to get the C# client of Riak running. But the nuget installation produces the following error on a modern `.netcore` style project (note that the platform is not `.netcore`. Any workarounds for this ? Couldnt find any other issues regarding this. Not sure why I am having this problem.

![riak](https://cloud.githubusercontent.com/assets/1297759/21444279/fb83f13a-c8bc-11e6-9bc3-23e3982e4f69.PNG)

**Comment by lukebakken** [comment]
Thank you for reporting this and for giving the .NET client a try.

It looks like `System.Configuration` is not going to be part of .NET core (dotnet/corefx#1348). In order to support .NET core, we would have to split out configuration into a separate dependency to allow "old style" configuration as well as what is supported in .NET Core.

At this time I recommend forking the code to remove the dependency on `System.Configuration`.

I don't know what the timeline is for us to support .NET Core but I will ask (@alexmoore)

Related to #325
